### ISSUE TITLE
/improve tool fails for Azure DevOps integration

### ISSUE THREAD

**Issue by okorneychuk** [Codium-ai/pr-agent#1033]
I do have AzureDevops integration and running the PR agent with docker.
## Problem
After the 0.23 release the `improve` tool throws the following error
![image](https://github.com/Codium-ai/pr-agent/assets/23223248/6b05a493-ef5a-4e5b-a0e7-1e30ba22b6fc)
This is happening because the `azuredevops_provider` provider does not implement this method and raises a `NotImplementedError` error

## Actual result
Throws an error

## Expected result
Only message logged, no error thrown

## Additional info
I reviewed the changes from the 0.23 release and found the following PR: https://github.com/Codium-ai/pr-agent/pull/1019
There is a change related to persistent comment
<img width="529" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/23223248/1e17a824-4a0e-4bf0-8131-894145f2e85e">

**Comment by mrT23** [comment]
try again, should work now

**Comment by okorneychuk** [comment]
I see it's not included in the latest tag. Can you please add some instructions to verify this locally?

**Comment by mrT23** [comment]
it is included. try

**Comment by okorneychuk** [comment]
No error while running the "/improve" command on the 0.23 version. Thank you
on the latest version it's still failing

**Comment by mrT23** [comment]
oh, i see. redeployed latest
